apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-management

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb.yaml
  - postgres.yaml
  - redis.yaml
  - user-service.yaml
  - task-service.yaml
  - notification-service.yaml
  - analytics-service.yaml
  - frontend.yaml
  - jaeger.yaml
  - ingress.yaml

# CI updates these tags via: kustomize edit set image task-management/<service>=<ecr-url>:<sha>
images:
  - name: task-management/frontend
    newName: 655700896650.dkr.ecr.ap-south-1.amazonaws.com/task-management/frontend
    newTag: latest
  - name: task-management/user-service
    newName: 655700896650.dkr.ecr.ap-south-1.amazonaws.com/task-management/user-service
    newTag: latest
  - name: task-management/task-service
    newName: 655700896650.dkr.ecr.ap-south-1.amazonaws.com/task-management/task-service
    newTag: latest
  - name: task-management/notification-service
    newName: 655700896650.dkr.ecr.ap-south-1.amazonaws.com/task-management/notification-service
    newTag: latest
  - name: task-management/analytics-service
    newName: 655700896650.dkr.ecr.ap-south-1.amazonaws.com/task-management/analytics-service
    newTag: latest
